name: build Re:VIEW PDF
on:
  push:
    branches:
      - master
jobs:
  build:
    name: generate PDF
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build PDF
      uses: takahashim/review-pdf-generator-action@master
    - name: upload PDF
      uses: takahashim/review-pdf-generator-action/upload-artifact@master
